name: 'Publish PDF Version Action'
description: 'Generate a new pdf for each version released'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  region:
    description: 'The region of the bucket'
    required: true
  accessKeyId:
    description: 'AWS access key to bucket'
    required: true
  secretAccessKey:
    description: 'AWS secret access key to bucket'
    required: true
  pdfName:
    description: 'Name of the pdf to be generated'
    required: true
  bucket:
    description: 'S3 bucket name'
    required: true
  baseUrl:
    description: 'S3 bucket url'
    required: true
  basePdf:
    description: 'Name of the base PDF'
    required: true
  outputPdfKey:
    description: 'The key where to save the latest pdf'
    required: true
outputs:
  url:
    description: 'The URL of the uploaded pdf'
